# Generated by Django 2.2 on 2019-04-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopapplications',
            name='application_date',
            field=models.DateTimeField(verbose_name='Application Date'),
        ),
    ]
