# Generated by Django 2.2 on 2019-05-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_register', '0003_auto_20190510_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='license_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='role',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_approved',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_gst',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_license_pdf',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_owner_id_proof',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_owner_photo',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shope_phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
