# Generated by Django 2.2 on 2019-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_register', '0002_auto_20190509_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
