# Generated by Django 2.2 on 2019-05-10 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_register', '0004_auto_20190510_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_photo', models.FileField(blank=True, upload_to='product_images')),
                ('quantity', models.IntegerField(max_length=20)),
                ('product_approved', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopadmin.Categories')),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_register.Shop')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopadmin.Units')),
            ],
        ),
    ]
