# Generated by Django 2.2 on 2019-05-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
