# Generated by Django 2.2 on 2019-05-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0002_auto_20190510_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_date',
            field=models.DateField(default=1, verbose_name='Date Field'),
            preserve_default=False,
        ),
    ]
