# Generated by Django 2.2 on 2019-05-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0003_product_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_date',
        ),
    ]
