# Generated by Django 2.2 on 2019-05-11 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0004_remove_product_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Field'),
            preserve_default=False,
        ),
    ]
