# Generated by Django 2.2 on 2019-05-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0005_product_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shopadmin.Categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop_register.Shop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shopadmin.Units'),
        ),
    ]
