# Generated by Django 2.2 on 2019-05-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0009_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='units',
        ),
    ]
