# Generated by Django 2.2 on 2019-05-10 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopadmin', '0002_auto_20190510_1935'),
        ('customer_register', '0003_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('order_time', models.DateTimeField(verbose_name='Order Time')),
                ('total_cost', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_register.UserProfile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopadmin.Product')),
            ],
        ),
    ]
