# Generated by Django 2.2 on 2019-05-10 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_register', '0003_userprofile_role'),
        ('product_management', '0004_remove_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer_register.UserProfile'),
            preserve_default=False,
        ),
    ]
